### ISSUE TITLE
i have error in starting

### ISSUE THREAD

**Issue by twitoorel1** [sk3106/NodeRP#7]
![Untitled](https://user-images.githubusercontent.com/64961625/233777828-11951b1e-bc04-4efd-b1d4-73d92afcc48c.png)

**Comment by sk3106** [comment]
Hi,

Thanks for reporting this issue! 

While I was away, a lot of modules seem to have changed. I think this one was sorted out in my test server, will check and push soon.

Regards,
SK

**Comment by sk3106** [comment]
@twitoorel1 This issue has been fixed in the latest update.
